<?php
/**
 * Keep media library structure
 *
 * Preserve the WordPress media library paths, when uploading images to Cloudflare Images, instead of the path
 * automatically generated by Cloudflare Images’ Universal Unique Identifier (UUID).
 *
 * @link https://vcore.au
 *
 * @package CF_Images
 * @subpackage CF_Images/App/Modules
 * @author Anton Vanyukov <a.vanyukov@vcore.ru>
 * @since 1.3.0  Moved out into its own module.
 */

namespace CF_Images\App\Modules;

if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Custom_Id class.
 *
 * @since 1.3.0
 */
class Custom_Id extends Module {

	/**
	 * Register UI components.
	 *
	 * @since 1.4.0
	 *
	 * @return void
	 */
	protected function register_ui() {
		$this->icon  = 'open-folder';
		$this->order = 30;
		$this->title = esc_html__( 'Keep media library structure', 'cf-images' );
	}

	/**
	 * Render module description.
	 *
	 * @since 1.4.0
	 *
	 * @param string $module  Module ID.
	 *
	 * @return void
	 */
	public function render_description( string $module ) {

		if ( $module !== $this->module ) {
			return;
		}
		?>
		<p>
			<?php esc_html_e( 'Preserve the WordPress media library paths, when uploading images to Cloudflare Images, instead of the path automatically generated by Cloudflare Images’ Universal Unique Identifier (UUID).', 'cf-images' ); ?>
		</p>
		<p>
			<?php esc_html_e( 'This does not convert already uploaded images. To change all the images to the new format (or back), you will need to perform bulk remove & upload.', 'cf-images' ); ?>
		</p>
		<?php

	}

	/**
	 * Init the module.
	 *
	 * @since 1.3.0
	 *
	 * @return void
	 */
	public function init() {
		add_filter( 'cf_images_upload_data', array( $this, 'use_custom_image_path' ) );
	}

	/**
	 * Set custom ID for image to use the custom paths in image URLs.
	 *
	 * @since 1.2.0
	 *
	 * @param array $data  Image data sent to the Cloudflare Images API.
	 *
	 * @return array
	 */
	public function use_custom_image_path( array $data ): array {

		if ( ! $this->is_enabled() ) {
			return $data;
		}

		if ( ! isset( $data['id'] ) && isset( $data['file']->postname ) ) {
			$data['id'] = $data['file']->postname;
		}

		return $data;

	}

}
