name: WPCS check

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "phpcs"
  phpcs:
    name: WPCS
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a WPCS check
      - name: Run WPCS check
        uses: 10up/wpcs-action@stable
        with:
          extra_args: '--report-json=./phpcs.json'

      #- name: Update summary
      #  run: |
      #    npx --yes github:10up/phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
      #    cat phpcs.md >> $GITHUB_STEP_SUMMARY
      #  if: always()
